네이버페이 결제형 수정
iamport/wordpress-iamport-for-woocommerce pull request #13
Opened 2021-08-04 07:30 UTC by hiddenpunch

허브형 direct 추가, naverUseCfm 을 직접 입력할 수 있도록 만듬

2021-08-04 10:04 UTC, SoleeChoi requested changes

2021-08-04 10:04 UTC, SoleeChoi commented on iamport-naverpay-ext.php
> +      $response['pg'] = 'naverpay';
위 251번째 줄에 $response['pg']를 이미 'naverpay'로 설정하고 있습니다.

사실 useManualPg가 true일때 pg값은 js단에서 알아서 셋팅되고 pay_method는 naverpay가 되고
useManualPg가 false일때는 pg값이 naverpay이고 pay_method는 card가 되어야 합니다.
따라서 251번째 줄과 위 260~263 코드는 아래와 같이 대체되어야 합니다.

저번에 설명드린대로 useManualPg가 false일때 pay_method를 naverpay로 보낸다고 해도
pay-iamport가 알아서 card로 바꿀테니 큰 문제는 없습니다만...
적어도 $response['pg']='naverpay'; 부분을 두군데서 가져갈 필요는 없어보입니다.


```php
if ($useManualPg) {
  $response['pay_method'] = 'naverpay';
} else {
  $response['pg'] = 'naverpay';
  $response['pay_method'] = 'card';
}
```

2021-08-04 10:04 UTC, SoleeChoi commented on assets/js/iamport.woocommerce.js
> +						if ( result.iamport.naverUseCfm )	  req_param.naverUseCfm = result.iamport.naverUseCfm;
이 아이도 일단은 삭제 부탁드립니다.

2021-08-04 10:04 UTC, SoleeChoi commented on assets/js/iamport.woocommerce.js
> +						if ( result.iamport.naverUseCfm )	  req_param.naverUseCfm = result.iamport.naverUseCfm;
이 아이도 일단은 삭제 부탁드립니다.

2021-08-05 01:46 UTC, hiddenpunch commented on assets/js/iamport.woocommerce.js
> +						if ( result.iamport.naverUseCfm )	  req_param.naverUseCfm = result.iamport.naverUseCfm;
넵!

2021-08-05 01:46 UTC, hiddenpunch commented on iamport-naverpay-ext.php
> +      $response['pg'] = 'naverpay';
아하 그렇군요 수정하겠습니다!

2021-08-05 02:47 UTC, SoleeChoi approved these changes

2021-08-05 02:48 UTC, merged