페이먼트월 PG 추가
iamport/wordpress-iamport-for-woocommerce pull request #23
Opened 2021-12-15 09:59 UTC by kdino

로컬에서 결제, 환불 테스트 완료했습니다.

2021-12-20 06:23 UTC, hiddenpunch commented
전액 환불완료가 되었을때 상태가 환불됨이 아니라 계속 취소됨에 있긴 한데, 큰 문제 없다면 괜찮을 것 같습니다

2021-12-20 06:23 UTC, hiddenpunch approved these changes

2021-12-20 08:47 UTC, SoleeChoi requested changes
이건 웬리와 논의 결과 core에서 paymentwall 연동이 완전히 안끝나보여서(운영모드에서 쓰고있는 가맹점 없다 함) 이걸 빠르게 merge하고 배포하는게 의미가 있는가 싶습니다.

2021-12-20 08:47 UTC, SoleeChoi commented on iamport-paymentwall.php
> +      if ($paymethod == 'vbank') {
pay-iamport 코드 보면 paymentwall은 vbank 연동이 덜 되어있는 것 같고 웬리 통해 확인 결과 그냥 일반적인 vbank 방식과 동일하여 vbank 정보가 있는 것으로 파악되는데 QR링크에 영수증 URL을 렌더링하는 것은 단순히 settle 뱅크 로직을 복붙한건가요?

2021-12-21 11:26 UTC, kdino commented on iamport-paymentwall.php
> +      if ($paymethod == 'vbank') {
vbank 부분 삭제했습니다!

2022-01-03 09:41 UTC, nonameP765 approved these changes

2022-01-04 01:23 UTC, merged