허브형 간편결제 연동 RE
iamport/wordpress-iamport-for-woocommerce pull request #6
Opened 2021-07-20 06:48 UTC by nonameP765

@hiddenpunch

2021-07-20 12:26 UTC, SoleeChoi requested changes

2021-07-20 12:26 UTC, SoleeChoi commented on iamport-alipay.php
> +                'description' => __( '알리페이 결제수단을 실제 적용할 PG사에 해당되는 정보를 직접 수동설정하실 수 있습니다. "{PG사 코드}.{PG상점아이디}" 의 형식으로 입력하실 수 있습니다. (예시 : alipay.IM_xxxx, kcp.IP123)', 'iamport-for-woocommerce' ),
신용카드와 동일하게 로직을 가져갈 수 있도록 comma(,)가 아닌 엔터 separated가 어떨까요?
그렇다면 문구 수정이 되어야할 것 같습니다.

2021-07-20 12:26 UTC, SoleeChoi commented on iamport-alipay.php
> +            $pgProvider = $manualPg[0];
금일(20일) 설명 드린 바와 같이, 해당 코드는 맨 앞에 작성된 하나의 값만 참조하고 있어
여러 개의 값을 등록할 경우 대비가 불가능합니다.

신용카드 gateway와 같이, 사용자가 2개 이상의 PG를 설정할 경우
(1) 체크아웃 페이지에서 해당 gateway 선택시 dropdown 메뉴가 렌더링 되도록 조치가 필요하며
(2) 이때 사용자가 선택한(select dom element의 value값) 값을 IMP.request_pay시 pg값으로 넘길 필요가 있어 보입니다.

해당 로직은 다른 gateway에서도 공통적으로 사용할 예정이고
특히 (1) 로직은 이미 신용카드 gateway에서 사용하고 있기 때문에
IamportHelper에 선언된 function을 재사용할 수 있어 보입니다.
또 필요한 로직이 있다면 되도록 IamportHelper에 정의해두면 중복된 코드 사용을 줄일 수 있을 것 같습니다.

2021-07-20 16:02 UTC, hiddenpunch commented on iamport-alipay.php
> +                'description' => __( '알리페이 결제수단을 실제 적용할 PG사에 해당되는 정보를 직접 수동설정하실 수 있습니다. "{PG사 코드}.{PG상점아이디}" 의 형식으로 입력하실 수 있습니다. (예시 : alipay.IM_xxxx, kcp.IP123)', 'iamport-for-woocommerce' ),
아주 좋은 생각인 것 같습니다!

2021-07-21 01:45 UTC, hiddenpunch commented on iamport-alipay.php
> +            $pgProvider = $manualPg[0];
무슨 말씀인지 이해했습니다.
pay_method를 구매가 고르고 드롭다운을 해서 pg사를 고르는 것이 구매자에 입장에서는 불편해 보이기는 한데
그 점만 제외하면 좋은 개선인 것 같습니다.
우선 이대로 진행하면 될까요?

2021-07-21 01:56 UTC, SoleeChoi commented on iamport-alipay.php
> +            $pgProvider = $manualPg[0];
저도 되게 이상하다고 생각했는데...신용카드가 일단 그렇게 되어있고
설정 화면에서 2개 이상을 등록한다는거 자체가 가맹점이 그렇게 의도한 것이라고 간주해도 될 것 같습니다.

이게 싫으면 1개만 등록하고, 1개만 등록한 경우엔 드롭다운 메뉴 노출 안 시키면 될 것 같아요!

2021-07-21 02:00 UTC, hiddenpunch commented on iamport-alipay.php
> +            $pgProvider = $manualPg[0];
아하 우선 그럼 여러개일때 드롭다운부터 해보겠습니다!

2021-07-23 01:36 UTC, closed without merging