payco dropdown
iamport/wordpress-iamport-for-woocommerce pull request #7
Opened 2021-07-21 06:57 UTC by hiddenpunch

payco dropdown 완료했습니다.
리뷰 부탁드립니다.

2021-07-21 08:33 UTC, SoleeChoi requested changes
신용카드 설정 화면에서는 아래와 같이
(1) 신용카드 결제시, 자동 적용될 PG 설정값 셋팅
(2) 신용카드 결제시, 적용될 PG설정값을 고객이 직접 지정
이렇게 나누어져 있고 해당 타이틀 하단에 description이 있는데
페이코도 통일성을 고려하고 고객의 이해도를 높이기 위해 이와 같이 해주실 수 있으실까요?

![image](https://user-images.githubusercontent.com/42368261/126456649-d9bbc816-df29-4a16-b0d8-4761156df83b.png)

2021-07-21 08:33 UTC, SoleeChoi commented on iamport-payco.php
> +                'description' => __( '아임포트 계정에 설정된 여러 PG사 / MID를 사용자의 선택에 따라 적용하는 기능을 활성화합니다. 신용카드 결제수단 선택 시, 세부 결제수단 선택창이 추가로 출력됩니다.', 'iamport-for-woocommerce' ),
신용카드 결제수단 선택시 -> PAYCO 결제수단 선택 시

2021-07-21 08:34 UTC, SoleeChoi commented
또한 현재 신용카드에 없는 기능인데...
시간 남으시면 PG설정 구매자 선택 한개만 설정한 경우엔 드롭다운 안나오게...가능할까요? ㅎㅎ

2021-07-21 08:36 UTC, hiddenpunch commented on iamport-payco.php
> +                'description' => __( '아임포트 계정에 설정된 여러 PG사 / MID를 사용자의 선택에 따라 적용하는 기능을 활성화합니다. 신용카드 결제수단 선택 시, 세부 결제수단 선택창이 추가로 출력됩니다.', 'iamport-for-woocommerce' ),
아하 그럼 신용카드처럼 자동 pg사도 만들고 드롭다운도 만들면 되는건가요?

2021-07-21 08:37 UTC, hiddenpunch commented
> 또한 현재 신용카드에 없는 기능인데...
> 시간 남으시면 PG설정 구매자 선택 한개만 설정한 경우엔 드롭다운 안나오게...가능할까요? ㅎㅎ

요것도 한 번 해보겠습니다 ㅎㅎ

2021-07-21 08:39 UTC, SoleeChoi commented on iamport-payco.php
> +                'description' => __( '아임포트 계정에 설정된 여러 PG사 / MID를 사용자의 선택에 따라 적용하는 기능을 활성화합니다. 신용카드 결제수단 선택 시, 세부 결제수단 선택창이 추가로 출력됩니다.', 'iamport-for-woocommerce' ),
아 아니다 이건 그냥 가시죠 제가 착각했네요 ㅎㅎ 죄송합니다

2021-07-21 09:51 UTC, hiddenpunch commented
1개일때는 dropdown 없애보았습니다!

2021-07-22 00:08 UTC, SoleeChoi requested changes

2021-07-22 00:08 UTC, SoleeChoi commented on iamport-payco.php
> +			$response['pay_method'] = 'payco'; //gateway ID가 iamport_payco로 돼있어서 기본적으로 pay_method : payco 적용되는 프론트 이슈 대응
얘는 PG사를 payco로 사용하는 경우니, pay_method가 payco가 아닌 card가 맞지 않을까요?

2021-07-22 00:08 UTC, SoleeChoi commented on lib/IamportHelper.php
> +            $uniquePG = count($pgOptions)==1?true:false; // only one pg => don't show dropdown
`$uniquePG = count($pgOptions)==1?true:false`를
`$uniquePG = count($pgOptions) == 1?;` 로 변경 가능할 것 같습니다.

2021-07-22 00:08 UTC, SoleeChoi commented on lib/IamportHelper.php
> +                <? foreach($pgOptions as $key=>$label) : ?>
어제 제가 잠깐 소개드린건데,
여기서 <?php가 아닌 <?를 사용하면 제 로컬 환경에서는 아래 <?=$key?>에 값이 들어가지 않아
결론적으로 `<option value selected></option>` 이 렌더링됩니다.

아래와 같이 <?php로 변경해보시고 라쿤 컴퓨터에서 정상 동작 하신다면 <?php로 변경 부탁드립니다.
```php
<?php foreach($pgOptions as $key=>$label) : ?>
```

2021-07-22 01:59 UTC, hiddenpunch commented on lib/IamportHelper.php
> +            $uniquePG = count($pgOptions)==1?true:false; // only one pg => don't show dropdown
아하 원래는 ture false가 아니라 string이어서 저렇게 했는데 좋은 방법 같아 보입니다!

2021-07-22 02:00 UTC, hiddenpunch commented on iamport-payco.php
> +			$response['pay_method'] = 'payco'; //gateway ID가 iamport_payco로 돼있어서 기본적으로 pay_method : payco 적용되는 프론트 이슈 대응
사실 pay_method를 어떤걸로 불러도 상관이 없는 것으로 보여서 그렇게 했는데 card로 바꿔놓을까요?

2021-07-22 02:00 UTC, hiddenpunch commented on lib/IamportHelper.php
> +                <? foreach($pgOptions as $key=>$label) : ?>
아하 한번 해보겠습니다!

2021-07-22 09:22 UTC, SoleeChoi approved these changes

2021-07-22 09:30 UTC, merged