dropdown kakaopay, alipay
iamport/wordpress-iamport-for-woocommerce pull request #8
Opened 2021-07-23 08:46 UTC by hiddenpunch

카카오페이와 일리페이도 dropdown으로 pg 선택하게 바꾸었습니다.
카카오페이에서 구버전과 신버전에 따라 kakao와 kakaopay로 key값이 바뀌는데 어떻게 처리해야 좋을지 잘 모르겠네요
시간되실 때 리뷰 부탁드립니다!

2021-07-26 04:10 UTC, SoleeChoi requested changes

2021-07-26 04:10 UTC, SoleeChoi commented on assets/js/iamport.woocommerce.js
> +		//if ( pay_method == 'kakao' )				pay_method = 'card';
주석 처리하신 부분은 pay_method(게이트웨이가 kakao면)가 kakao면, IMP.request_pay시 pay_method를 card로 강제하는 로직입니다.

1) 게이트웨이가 카카오페이(pg: kakaopay 또는 kakao)면, pay_method는 항상 card가 되어야 하고
2) 게이트웨이가 카카오페이지만, 다른 PG사로 다이렉트 호출하는거라면(pg: html5_inicis, kcp 등) pay_method는 kakaopay가 되어야 합니다.

기존에는 1번 케이스밖에 없어서 위 로직이 생겨났는데
이번에 작업하면서 2번 케이스가 생기므로 해당 로직을 주석처리하신 것으로 보입니다.
하지만 주석처리할 경우 pay_method가 항상 kakao로 들어갑니다.

이 경우 1번 케이스에서는 어차피 PAY-IAMPORT에서 pay_method를 card로 치환해 문제가 없지만
2번 케이스는 대응이 되지 않습니다.

따라서 이를 대응하기 위한 코드가 필요한데
아무래도 iamport-kakao.php의 iamport_payment_info function에서 처리하는 것이 옳아보입니다.

필요한 코드는 아래 해당 로직에서 다시 설명드리겠습니다.

2021-07-26 04:10 UTC, SoleeChoi commented on iamport-kakao.php
>  		return $response;
여기서 $response에 pg 외에 pay_method값 설정이 필요합니다.

위에서 안내드린 1번 케이스는 !$useManualPg일 경우이기 때문에
if (!useManualPg)인 경우엔 $response['pay_method'] = 'card'가 되어야 합니다.

2번 케이스는 $useManualPg && $this->use_new_version === 'yes'인 경우입니다.
이때는 $response['pay_method'] = 'kakaopay'가 되어야 합니다.

정리해보면 아래와 같습니다.

```php
$useNewVersion = $this->use_new_version === 'yes';
if (!$useManualPg) {
    $response['pay_method'] = 'card';
    // 다른 로직
} else if ($useNewVersion) {
    $response['pay_method'] = 'kakaopay';
}
```

2021-07-26 04:10 UTC, SoleeChoi commented on iamport-kakao.php
>  		return $response;
참고로 pg: html5_inicis + pay_method: kakaopay를 직접 테스트해보시면 됩니다.
현재는 게이트웨이 - 카카오페이 설정에서 PG설정 구매자 선택을 html5_inicis: 이니시스로 추가해보면
카카오페이가 직접 호출되지 않고, 기존의 이니시스 결제창이 뜨는 것을 확인해보실 수 있는데
이는 현재 pay_method가 kakao로 들어가고 있기 때문입니다.

작업 후 테스트 마치시고 다시 PR 부탁드립니다.

2021-07-26 04:26 UTC, SoleeChoi commented on iamport-kakao.php
>  		return $response;
간편결제 직접 호출을 위해 테스트 가능한 PG모듈 설정 정보 [노션](https://www.notion.so/chaifinance/28cae26561b0462da23b66919982dcfe)에 정리해두었습니다.

2021-07-27 01:47 UTC, hiddenpunch commented on iamport-kakao.php
>  		return $response;
세심한 리뷰 감사합니다~!
html5_inicis의 경우에서 의문점이 생기는데, use_new_version == "no' 이고, html5_inicis에서 카카오페이 direct 호출을 원하는 상황에서는 use_new_version이 no 이기 때문에 pay_method가 kakao가 되어야 할 것 같은데 이 경우는 디디가 말씀하셨던대로 카카오페이가 직접 호출되지 않습니다. 이와 같은 경우에는 pay_method를 version을 우선시 해서 kakao로 해야 할지 아니면 direct 호출을 우선시 해서 kakaopay로 해야할지 잘 모르겠습니다.

2021-07-27 05:53 UTC, hiddenpunch commented
@SoleeChoi 말씀하신 부분 고쳐서 올렸습니다(테스트 완료) 시간되실 때 확인 부탁드려요!
그런데 구버전 kakao의 경우는 계속 txn 에러가 나는데 이 부분은 어떻게 해야할지 잘 모르겠습니다

2021-07-28 05:44 UTC, hiddenpunch commented
@SoleeChoi 말씀하신 부분 수정해서 push 했습니다!

2021-07-28 05:57 UTC, SoleeChoi approved these changes
잘 됩니다! 수고하셨습니다 :)

2021-07-28 06:00 UTC, hiddenpunch commented
와! 감사합니다 ㅎㅎ

2021-07-28 08:32 UTC, merged